
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  pull_request:
    branches: [ "main", "version/0.2.1" ]

jobs:
  build-gradle-project:
    name: Build Gradle Project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-build

      - name: "Gradle: Build"
        uses: ./.github/actions/run-tests
        with:
          command: ./gradlew build check ${{ env.GRADLE_ARGS }}
      - name: "Gradle: Publish (Main & Release Only)"
        uses: gradle/gradle-build-action@v3.2.1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          arguments: publishAllPublicationsToGitHubPackagesRepository ${{ env.GRADLE_ARGS }}
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
